### ISSUE TITLE
Support for decoding frames

### ISSUE THREAD

**Issue by TomMD** [thoughtpolice/pcap-conduit#1]
Were I to send a patch, would you consider adding support for decoding the bytestring into L2/L3 headers and a payload?  This would probably include a new build dep on network-data (which might need improved or replaced first).

**Comment by thoughtpolice** [comment]
I'd be interested in helping with this. Ideally, I think there should be like this (if I'm understanding the `network-data` API correctly):
- A `network-data-conduit` package that provides a `Conduit` which transforms ByteStrings into `L3Header` values, i.e. something like:
  
  ``` haskell
  -- | Transforms ByteStrings into L3 frames. 
  -- The output type is the product is the frame header.
  l3FrameConduit :: (Monad m, L3Frame h a c) => Conduit ByteString m h
  l3FrameConduit = ...
  ```
- Then, `pcap-conduit` can depend on `network-data-conduit` and we can define two extra `Source` types that merely fuse the existing sources with the frame conduit:
  
  ``` haskell
  -- | Read pcap data from a file, and translate it into IP frames.
  sourceOffline_L3 :: (L3Header h a c, MonadIO m) => FilePath -> Source m h
  sourceOffline_L3 path = sourceOffline path $= l3FrameConduit
  
  -- | Read pcap data from an interface, and translate it into IP frames.
  sourceLive_L3 :: (L3Header h a c, MonadIO m) => ... -> Source m h
  sourceLive_L3 ... = sourceLive ... $= l3FrameConduit
  ```

I don't have a typechecker handy so some of this is probably wrong, but I think you get the idea. Obviously these code samples are wrong because you'd need to munge the `ByteString` and `PktHdr` combo together before giving it to `decode` in Data.Serialize, but you get the gist. This also would allow people to decode any `ByteString` into a `Frame` in a Conduit with a seperate package, so it'd be more generally useful.

I'd be more than willing to  write up a basic `network-data-conduit` package and tie it into `pcap-conduit` for you, if you'd like to make improvements to `network-data` yourself. Writing such adapters is very quick and painless normally, especially considering you could define most of this using the `conduit-cereal` adapter.
